-- Ken's TwitterKeywords list. Safe to re-run.
INSERT INTO "TwitterKeywords" ("Id", "Keyword", "NormalizedKeyword", "Category", "Weight", "IsActive") VALUES
(1, 'achilles', 'achilles', 'Injury', 1.0, true),
(2, 'ankle', 'ankle', 'Injury', 1.0, true),
(3, 'available', 'available', 'Availability', 0.6, true),
(5, 'bruise', 'bruise', 'Injury', 1.0, true),
(6, 'bug', 'bug', 'Injury', 0.3, true),
(7, 'calf', 'calf', 'Injury', 1.0, true),
(8, 'chest', 'chest', 'Injury', 0.6, true),
(9, 'cleared to play', 'cleared to play', 'Availability', 1.0, true),
(10, 'concussion', 'concussion', 'Injury', 1.0, true),
(11, 'day to day', 'day to day', 'Availability', 1.0, true),
(12, 'doubtful', 'doubtful', 'Availability', 1.0, true),
(13, 'elbow', 'elbow', 'Injury', 1.0, true),
(14, 'expected to play', 'expected to play', 'Availability', 1.0, true),
(15, 'eye', 'eye', 'Injury', 0.3, true),
(16, 'fatigue', 'fatigue', 'Injury', 1.0, true),
(17, 'finger', 'finger', 'Injury', 1.0, true),
(18, 'food poisoning', 'food poisoning', 'Injury', 1.0, true),
(19, 'foot', 'foot', 'Injury', 0.6, true),
(22, 'going to start', 'going to start', 'Availability', 1.0, true),
(23, 'gtd', 'gtd', 'Availability', 1.0, true),
(24, 'hamstring', 'hamstring', 'Injury', 1.0, true),
(25, 'hip', 'hip', 'Injury', 0.6, true),
(26, 'illness', 'illness', 'Injury', 1.0, true),
(27, 'inactive', 'inactive', 'Availability', 1.0, true),
(28, 'injury', 'injury', 'Injury', 1.0, true),
(30, 'is out', 'is out', 'Availability', 1.0, true),
(31, 'is starting', 'is starting', 'Availability', 1.0, true),
(33, 'knee', 'knee', 'Injury', 1.0, true),
(34, 'leg', 'leg', 'Injury', 0.6, true),
(35, 'lineup', 'lineup', 'Availability', 0.6, true),
(36, 'lock room', 'lock room', 'TeamActivity', 1.0, true),
(37, 'neck', 'neck', 'Injury', 0.6, true),
(38, 'nose', 'nose', 'Injury', 0.6, true),
(39, 'out indefinitely', 'out indefinitely', 'Availability', 1.0, true),
(40, 'pectoral', 'pectoral', 'Injury', 1.0, true),
(41, 'personal', 'personal', 'Personal', 0.3, true),
(42, 'probable', 'probable', 'Availability', 1.0, true),
(43, 'recovery', 'recovery', 'Injury', 1.0, true),
(44, 'rest', 'rest', 'Availability', 0.3, true),
(45, 'rib', 'rib', 'Injury', 1.0, true),
(46, 'ribs', 'ribs', 'Injury', 1.0, true),
(47, 'shootaround', 'shootaround', 'TeamActivity', 1.0, true),
(48, 'shoulder', 'shoulder', 'Injury', 1.0, true),
(49, 'sick', 'sick', 'Injury', 1.0, true),
(51, 'starters', 'starters', 'Availability', 1.0, true),
(52, 'stomach', 'stomach', 'Injury', 1.0, true),
(53, 'surgery', 'surgery', 'Injury', 1.0, true),
(54, 'suspension', 'suspension', 'Discipline', 1.0, true),
(55, 'thumb', 'thumb', 'Injury', 1.0, true),
(57, 'start tonight', 'start tonight', 'Availability', 1.0, true),
(58, 'will not play', 'will not play', 'Availability', 1.0, true),
(59, 'will not start', 'will not start', 'Availability', 1.0, true),
(60, 'will play', 'will play', 'Availability', 1.0, true),
(61, 'will start', 'will start', 'Availability', 1.0, true),
(62, 'wrist', 'wrist', 'Injury', 1.0, true),
(63, 'dislocated', 'dislocated', 'Injury', 1.0, true),
(64, 'twist', 'twist', 'Injury', 0.6, true),
(65, 'minutes', 'minutes', 'Availability', 0.3, true),
(66, 'plantar fasciitis', 'plantar fasciitis', 'Injury', 1.0, true),
(67, 'sore', 'sore', 'Injury', 1.0, true),
(68, 'hurting', 'hurting', 'Injury', 1.0, true),
(69, 'checks back in', 'checks back in', 'Availability', 1.0, true),
(70, 'targeting', 'targeting', 'Transaction', 0.3, true),
(72, 'month', 'month', 'Availability', 0.3, true),
(73, 'unlikely to play', 'unlikely to play', 'Availability', 1.0, true),
(75, 'suspended', 'suspended', 'Discipline', 1.0, true),
(76, 'traded', 'traded', 'Transaction', 1.0, true),
(77, 'out tonight', 'out tonight', 'Availability', 1.0, true),
(78, 'out tomorrow', 'out tomorrow', 'Availability', 1.0, true),
(79, 'morning shoot', 'morning shoot', 'TeamActivity', 1.0, true),
(80, 'gastroenteritis', 'gastroenteritis', 'Injury', 1.0, true),
(81, 'questionable', 'questionable', 'Availability', 1.0, true),
(82, 'is active', 'is active', 'Availability', 1.0, true),
(83, 'should play', 'should play', 'Availability', 1.0, true),
(84, 'will likely play', 'will likely play', 'Availability', 1.0, true),
(86, 'will not return', 'will not return', 'Availability', 1.0, true),
(87, 'injured', 'injured', 'Injury', 1.0, true),
(88, 'spasms', 'spasms', 'Injury', 1.0, true),
(90, 'good to go', 'good to go', 'Availability', 1.0, true),
(91, 'kneecap', 'kneecap', 'Injury', 1.0, true),
(92, 'patella', 'patella', 'Injury', 1.0, true),
(93, 'is playing', 'is playing', 'Availability', 1.0, true),
(94, 'returned', 'returned', 'Availability', 0.6, true),
(95, 'back with', 'back with', 'Availability', 0.3, true),
(96, 'ready to go', 'ready to go', 'Availability', 1.0, true),
(97, 'ruled out', 'ruled out', 'Availability', 1.0, true),
(98, 'oblique', 'oblique', 'Injury', 1.0, true),
(99, 'muscle', 'muscle', 'Injury', 0.6, true),
(100, 'strained', 'strained', 'Injury', 1.0, true),
(101, 'practiced', 'practiced', 'TeamActivity', 1.0, true),
(102, 'sprain', 'sprain', 'Injury', 1.0, true),
(103, 'rays', 'rays', 'Injury', 0.3, true),
(106, 'lower', 'lower', 'Injury', 0.3, true),
(107, 'upper', 'upper', 'Injury', 0.3, true),
(108, 'toe', 'toe', 'Injury', 1.0, true),
(109, 'sprained', 'sprained', 'Injury', 1.0, true),
(111, 'soreness', 'soreness', 'Injury', 1.0, true),
(112, 'ailing', 'ailing', 'Injury', 1.0, true),
(114, 'ruled', 'ruled', 'Availability', 0.3, true),
(115, 'groin', 'groin', 'Injury', 1.0, true),
(116, 'practice', 'practice', 'TeamActivity', 0.6, true),
(117, 'contusion', 'contusion', 'Injury', 1.0, true),
(118, 'limp', 'limp', 'Injury', 1.0, true),
(119, 'mri', 'mri', 'Injury', 1.0, true),
(120, 'laceration', 'laceration', 'Injury', 1.0, true),
(121, 'chin', 'chin', 'Injury', 0.6, true),
(122, 'lip', 'lip', 'Injury', 0.6, true),
(123, 'trade', 'trade', 'Transaction', 0.6, true),
(124, 'offered', 'offered', 'Transaction', 0.3, true),
(126, 'road trip', 'road trip', 'TeamActivity', 1.0, true),
(127, 'funeral', 'funeral', 'Personal', 1.0, true),
(129, 'go tonight', 'go tonight', 'Availability', 1.0, true),
(130, 'contract', 'contract', 'Transaction', 0.6, true),
(131, 'quad', 'quad', 'Injury', 1.0, true),
(132, 'ejected', 'ejected', 'Discipline', 1.0, true),
(133, 'doctor', 'doctor', 'Injury', 0.6, true),
(134, 'bereavement', 'bereavement', 'Personal', 1.0, true),
(136, 'will sit', 'will sit', 'Availability', 1.0, true),
(137, 'wont play', 'wont play', 'Availability', 1.0, true),
(138, 'listed out', 'listed out', 'Availability', 1.0, true),
(139, 'intent to play', 'intent to play', 'Availability', 1.0, true),
(140, 'not starting', 'not starting', 'Availability', 1.0, true),
(141, 'wont return', 'wont return', 'Availability', 1.0, true),
(142, 'questionable to return', 'questionable to return', 'Availability', 1.0, true),
(143, 'doubtful to return', 'doubtful to return', 'Availability', 1.0, true),
(144, 'probable to return', 'probable to return', 'Availability', 1.0, true),
(145, 'available to return', 'available to return', 'Availability', 1.0, true),
(147, 'out again', 'out again', 'Availability', 1.0, true),
(150, 'out versus', 'out versus', 'Availability', 1.0, true),
(151, 'hopeful to play', 'hopeful to play', 'Availability', 1.0, true),
(152, 'hopes to play', 'hopes to play', 'Availability', 1.0, true),
(153, 'will miss tonight', 'will miss tonight', 'Availability', 1.0, true),
(155, 'plans to play', 'plans to play', 'Availability', 1.0, true),
(156, 'will return tonight', 'will return tonight', 'Availability', 1.0, true),
(158, 'still out', 'still out', 'Availability', 1.0, true),
(160, 'may not go', 'may not go', 'Availability', 1.0, true),
(161, 'questionable to play', 'questionable to play', 'Availability', 1.0, true),
(163, 'is resting', 'is resting', 'Availability', 1.0, true),
(164, 'available to play', 'available to play', 'Availability', 1.0, true),
(165, 'under the weather', 'under the weather', 'Injury', 1.0, true),
(166, 'likely out', 'likely out', 'Availability', 1.0, true),
(167, 'late scratch', 'late scratch', 'Availability', 1.0, true),
(168, 'will be available', 'will be available', 'Availability', 1.0, true),
(169, 'doubtful to play', 'doubtful to play', 'Availability', 1.0, true),
(170, 'locker room', 'locker room', 'TeamActivity', 1.0, true),
(171, 'wont be with', 'wont be with', 'Availability', 1.0, true),
(172, 'paternity', 'paternity', 'Personal', 1.0, true),
(173, 'sit tonight', 'sit tonight', 'Availability', 1.0, true),
(174, 'play tonight', 'play tonight', 'Availability', 1.0, true),
(175, 'play today', 'play today', 'Availability', 1.0, true),
(176, 'sit today', 'sit today', 'Availability', 1.0, true),
(177, 'start today', 'start today', 'Availability', 1.0, true),
(178, 'day-to-day', 'day to day', 'Availability', 1.0, true),
(179, 'not expected to play', 'not expected to play', 'Availability', 1.0, true),
(180, 'will be active', 'will be active', 'Availability', 1.0, true),
(182, 'ready to play', 'ready to play', 'Availability', 1.0, true),
(183, 'hand', 'hand', 'Injury', 0.3, true),
(184, 'not yet ready', 'not yet ready', 'Availability', 1.0, true),
(186, 'back tomorrow', 'back tomorrow', 'Availability', 1.0, true),
(188, 'deal to send', 'deal to send', 'Transaction', 1.0, true),
(189, 'listed as active', 'listed as active', 'Availability', 1.0, true),
(190, 'out vs', 'out vs', 'Availability', 1.0, true),
(191, 'to play tonight', 'to play tonight', 'Availability', 1.0, true),
(192, 'kidney', 'kidney', 'Injury', 1.0, true),
(193, 'walkthrough', 'walkthrough', 'TeamActivity', 1.0, true),
(194, 'playing', 'playing', 'Availability', 0.3, true),
(195, 'will miss', 'will miss', 'Availability', 1.0, true),
(196, 'child', 'child', 'Personal', 0.6, true),
(197, 'starting', 'starting', 'Availability', 0.3, true),
(200, 'start tomorrow', 'start tomorrow', 'Availability', 1.0, true),
(202, 'likely play', 'likely play', 'Availability', 1.0, true),
(204, 'play vs', 'play vs', 'Availability', 1.0, true),
(205, 'tear', 'tear', 'Injury', 0.6, true),
(206, 'will be out', 'will be out', 'Availability', 1.0, true),
(207, 'return date', 'return date', 'Availability', 1.0, true),
(208, 'all out', 'all out', 'Availability', 0.3, true),
(209, 'will warm up', 'will warm up', 'Availability', 1.0, true),
(210, 'injury report', 'injury report', 'Injury', 1.0, true),
(211, 'scratch', 'scratch', 'Availability', 0.6, true),
(212, 'bone', 'bone', 'Injury', 0.6, true),
(213, 'isnt expected to play', 'isnt expected to play', 'Availability', 1.0, true),
(214, 'remains out', 'remains out', 'Availability', 1.0, true),
(217, 'wont be playing', 'wont be playing', 'Availability', 1.0, true),
(218, 'expected to sit', 'expected to sit', 'Availability', 1.0, true),
(219, 'returns tonight', 'returns tonight', 'Availability', 1.0, true),
(220, 'return today', 'return today', 'Availability', 1.0, true),
(221, 'training room', 'training room', 'Injury', 1.0, true),
(222, 'to play today', 'to play today', 'Availability', 1.0, true),
(223, 'mcl', 'mcl', 'Injury', 1.0, true),
(224, 'acl', 'acl', 'Injury', 1.0, true),
(225, 'will return', 'will return', 'Availability', 1.0, true),
(226, 'adductor', 'adductor', 'Injury', 1.0, true),
(227, 'might play', 'might play', 'Availability', 1.0, true),
(228, 'on track', 'on track', 'Availability', 0.6, true),
(229, 'play tomorrow', 'play tomorrow', 'Availability', 1.0, true),
(230, 'brace', 'brace', 'Injury', 1.0, true),
(231, 'right arm', 'right arm', 'Injury', 1.0, true),
(232, 'left arm', 'left arm', 'Injury', 1.0, true),
(233, 'right leg', 'right leg', 'Injury', 1.0, true),
(234, 'left leg', 'left leg', 'Injury', 1.0, true),
(235, 'out today', 'out today', 'Availability', 1.0, true),
(237, 'sending', 'sending', 'Transaction', 0.3, true),
(238, 'pick', 'pick', 'Transaction', 0.3, true),
(239, 'round', 'round', 'Transaction', 0.3, true),
(240, 'flu', 'flu', 'Injury', 1.0, true),
(241, 'gametime', 'gametime', 'Availability', 0.6, true),
(242, 'protocols', 'protocols', 'Injury', 1.0, true),
(243, 'covid', 'covid', 'Injury', 1.0, true),
(244, 'infection', 'infection', 'Injury', 1.0, true),
(245, 'tooth', 'tooth', 'Injury', 0.6, true),
(246, 'sign', 'sign', 'Transaction', 0.3, true),
(247, 'blood', 'blood', 'Injury', 0.6, true),
(248, 'face', 'face', 'Injury', 0.3, true),
(250, 'contracts', 'contracts', 'Transaction', 0.6, true),
(252, 'waive', 'waive', 'Transaction', 1.0, true),
(253, 'five', 'five', 'Availability', 0.3, true),
(254, 'bench', 'bench', 'Availability', 0.3, true),
(257, 'downgraded', 'downgraded', 'Availability', 1.0, true),
(258, 'upgraded', 'upgraded', 'Availability', 1.0, true),
(259, 'start', 'start', 'Availability', 0.3, true)
ON CONFLICT ("Id") DO UPDATE SET
  "Keyword" = EXCLUDED."Keyword",
  "NormalizedKeyword" = EXCLUDED."NormalizedKeyword",
  "Category" = EXCLUDED."Category",
  "Weight" = EXCLUDED."Weight";
