CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260723163527_InitialCreate') THEN
    CREATE TABLE "TweetUsers" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "TwitterUserId" character varying(50) NOT NULL,
        "ScreenUsername" character varying(100) NOT NULL,
        "DisplayName" character varying(100) NOT NULL,
        "ImageUrl" character varying(200) NOT NULL,
        "IsVerified" boolean NOT NULL,
        CONSTRAINT "PK_TweetUsers" PRIMARY KEY ("Id"),
        CONSTRAINT "AK_TweetUsers_TwitterUserId" UNIQUE ("TwitterUserId")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260723163527_InitialCreate') THEN
    CREATE TABLE "TwitterLists" (
        "ListId" bigint NOT NULL,
        "SportId" integer NOT NULL,
        "Name" character varying(200) NOT NULL,
        "IsActive" boolean NOT NULL,
        "LastFetchedUnix" bigint NOT NULL,
        "LastFetchedAt" timestamp with time zone,
        "LastTweetCount" integer NOT NULL,
        CONSTRAINT "PK_TwitterLists" PRIMARY KEY ("ListId")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260723163527_InitialCreate') THEN
    CREATE TABLE "Tweets" (
        "TweetId" character varying(50) NOT NULL,
        "TwitterUserId" character varying(50) NOT NULL,
        "SportId" integer NOT NULL,
        "CreatedDate" timestamp with time zone NOT NULL,
        "RetweetDate" timestamp with time zone,
        "DateAdded" timestamp with time zone,
        "IsRetweet" boolean,
        "IsSourceTweet" boolean,
        "RetweetUserScreenName" character varying(100),
        "Text" text NOT NULL,
        "RetweetCount" integer,
        "Followers" integer,
        "SourceTweetId" character varying(50),
        "SourceTweetUserScreenName" character varying(100),
        CONSTRAINT "PK_Tweets" PRIMARY KEY ("TweetId"),
        CONSTRAINT "FK_Tweets_TweetUsers_TwitterUserId" FOREIGN KEY ("TwitterUserId") REFERENCES "TweetUsers" ("TwitterUserId") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260723163527_InitialCreate') THEN
    CREATE TABLE "TweetImages" (
        "TweetId" character varying(50) NOT NULL,
        "DisplayOrder" smallint NOT NULL,
        "ImageUrl" character varying(500) NOT NULL,
        CONSTRAINT "PK_TweetImages" PRIMARY KEY ("TweetId", "DisplayOrder"),
        CONSTRAINT "FK_TweetImages_Tweets_TweetId" FOREIGN KEY ("TweetId") REFERENCES "Tweets" ("TweetId") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260723163527_InitialCreate') THEN
    CREATE INDEX "IX_Tweets_CreatedDate" ON "Tweets" ("CreatedDate");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260723163527_InitialCreate') THEN
    CREATE INDEX "IX_Tweets_SportId_CreatedDate" ON "Tweets" ("SportId", "CreatedDate");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260723163527_InitialCreate') THEN
    CREATE INDEX "IX_Tweets_TwitterUserId" ON "Tweets" ("TwitterUserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260723163527_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_TweetUsers_ScreenUsername" ON "TweetUsers" ("ScreenUsername");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260723163527_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_TweetUsers_TwitterUserId" ON "TweetUsers" ("TwitterUserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260723163527_InitialCreate') THEN
    CREATE INDEX "IX_TwitterLists_SportId" ON "TwitterLists" ("SportId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260723163527_InitialCreate') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260723163527_InitialCreate', '10.0.10');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260723165624_AddMediaTypeAndVerification') THEN
    ALTER TABLE "TweetUsers" ADD "IsBlueVerified" boolean NOT NULL DEFAULT FALSE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260723165624_AddMediaTypeAndVerification') THEN
    ALTER TABLE "TweetUsers" ADD "LastSeenAt" timestamp with time zone;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260723165624_AddMediaTypeAndVerification') THEN
    ALTER TABLE "TweetUsers" ADD "VerifiedType" character varying(50);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260723165624_AddMediaTypeAndVerification') THEN
    ALTER TABLE "TweetImages" ADD "DurationMillis" integer;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260723165624_AddMediaTypeAndVerification') THEN
    ALTER TABLE "TweetImages" ADD "MediaType" character varying(20) NOT NULL DEFAULT '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260723165624_AddMediaTypeAndVerification') THEN
    ALTER TABLE "TweetImages" ADD "VideoUrl" character varying(500);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260723165624_AddMediaTypeAndVerification') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260723165624_AddMediaTypeAndVerification', '10.0.10');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260723170815_RenameTweetImagesToTweetMedia') THEN
    DROP TABLE "TweetImages";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260723170815_RenameTweetImagesToTweetMedia') THEN
    CREATE TABLE "TweetMedia" (
        "TweetId" character varying(50) NOT NULL,
        "DisplayOrder" smallint NOT NULL,
        "ImageUrl" character varying(500) NOT NULL,
        "MediaType" character varying(20) NOT NULL,
        "VideoUrl" character varying(500),
        "DurationMillis" integer,
        CONSTRAINT "PK_TweetMedia" PRIMARY KEY ("TweetId", "DisplayOrder"),
        CONSTRAINT "FK_TweetMedia_Tweets_TweetId" FOREIGN KEY ("TweetId") REFERENCES "Tweets" ("TweetId") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260723170815_RenameTweetImagesToTweetMedia') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260723170815_RenameTweetImagesToTweetMedia', '10.0.10');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260723210544_AddDateAddedIndexes') THEN
    CREATE INDEX "IX_Tweets_DateAdded" ON "Tweets" ("DateAdded");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260723210544_AddDateAddedIndexes') THEN
    CREATE INDEX "IX_Tweets_SportId_DateAdded" ON "Tweets" ("SportId", "DateAdded");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260723210544_AddDateAddedIndexes') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260723210544_AddDateAddedIndexes', '10.0.10');
    END IF;
END $EF$;
COMMIT;

