// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RotoMonsterTwitter.Model.Data;

#nullable disable

namespace RotoMonsterTwitter.Model.Migrations
{
    [DbContext(typeof(TwitterDbContext))]
    [Migration("20260727170138_AddUserNewsTopFlags")]
    partial class AddUserNewsTopFlags
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RotoMonsterTwitter.Model.Entities.Tweet", b =>
                {
                    b.Property<string>("TweetId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateAdded")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Followers")
                        .HasColumnType("integer");

                    b.Property<bool?>("IsRetweet")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsSourceTweet")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("RetweetCount")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("RetweetDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RetweetUserScreenName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SourceTweetId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("SourceTweetUserScreenName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("SportId")
                        .HasColumnType("integer");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TwitterUserId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("TweetId");

                    b.HasIndex("CreatedDate");

                    b.HasIndex("DateAdded");

                    b.HasIndex("ProcessedAt");

                    b.HasIndex("TwitterUserId");

                    b.HasIndex("SportId", "CreatedDate");

                    b.HasIndex("SportId", "DateAdded");

                    b.ToTable("Tweets", (string)null);
                });

            modelBuilder.Entity("RotoMonsterTwitter.Model.Entities.TweetKeyword", b =>
                {
                    b.Property<string>("TweetId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("KeywordId")
                        .HasColumnType("integer");

                    b.Property<int>("Occurrences")
                        .HasColumnType("integer");

                    b.HasKey("TweetId", "KeywordId");

                    b.HasIndex("KeywordId");

                    b.ToTable("TweetKeywords", (string)null);
                });

            modelBuilder.Entity("RotoMonsterTwitter.Model.Entities.TweetMedia", b =>
                {
                    b.Property<string>("TweetId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<short>("DisplayOrder")
                        .HasColumnType("smallint");

                    b.Property<int?>("DurationMillis")
                        .HasColumnType("integer");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("VideoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("TweetId", "DisplayOrder");

                    b.ToTable("TweetMedia", (string)null);
                });

            modelBuilder.Entity("RotoMonsterTwitter.Model.Entities.TweetPlayer", b =>
                {
                    b.Property<string>("TweetId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Confidence")
                        .HasPrecision(3, 2)
                        .HasColumnType("numeric(3,2)");

                    b.Property<string>("MatchType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("Occurrences")
                        .HasColumnType("integer");

                    b.HasKey("TweetId", "PlayerId");

                    b.HasIndex("Confidence");

                    b.HasIndex("PlayerId");

                    b.ToTable("TweetPlayers", (string)null);
                });

            modelBuilder.Entity("RotoMonsterTwitter.Model.Entities.TweetTeam", b =>
                {
                    b.Property<string>("TweetId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Confidence")
                        .HasPrecision(3, 2)
                        .HasColumnType("numeric(3,2)");

                    b.Property<string>("MatchType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("Occurrences")
                        .HasColumnType("integer");

                    b.HasKey("TweetId", "TeamId");

                    b.HasIndex("TeamId");

                    b.ToTable("TweetTeams", (string)null);
                });

            modelBuilder.Entity("RotoMonsterTwitter.Model.Entities.TweetUser", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsBlueVerified")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsNews")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsTop")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ScreenUsername")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("TwitterUserId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("VerifiedType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("IsNews");

                    b.HasIndex("IsTop");

                    b.HasIndex("ScreenUsername")
                        .IsUnique();

                    b.HasIndex("TwitterUserId")
                        .IsUnique();

                    b.ToTable("TweetUsers", (string)null);
                });

            modelBuilder.Entity("RotoMonsterTwitter.Model.Entities.TwitterKeyword", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Keyword")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NormalizedKeyword")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("Weight")
                        .HasPrecision(3, 2)
                        .HasColumnType("numeric(3,2)");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("NormalizedKeyword");

                    b.ToTable("TwitterKeywords", (string)null);
                });

            modelBuilder.Entity("RotoMonsterTwitter.Model.Entities.TwitterList", b =>
                {
                    b.Property<long>("ListId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastFetchedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("LastFetchedUnix")
                        .HasColumnType("bigint");

                    b.Property<int>("LastTweetCount")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("SportId")
                        .HasColumnType("integer");

                    b.HasKey("ListId");

                    b.HasIndex("SportId");

                    b.ToTable("TwitterLists", (string)null);
                });

            modelBuilder.Entity("RotoMonsterTwitter.Model.Entities.TwitterPlayer", b =>
                {
                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("FullNameOnly")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NormalizedFullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("NormalizedLastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("SportId")
                        .HasColumnType("integer");

                    b.Property<int?>("TeamId")
                        .HasColumnType("integer");

                    b.HasKey("PlayerId");

                    b.HasIndex("NormalizedLastName");

                    b.HasIndex("SportId");

                    b.HasIndex("TeamId");

                    b.ToTable("TwitterPlayers", (string)null);
                });

            modelBuilder.Entity("RotoMonsterTwitter.Model.Entities.TwitterPlayerAlias", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Alias")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("NormalizedAlias")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedAlias");

                    b.HasIndex("PlayerId");

                    b.ToTable("TwitterPlayerAliases", (string)null);
                });

            modelBuilder.Entity("RotoMonsterTwitter.Model.Entities.TwitterTeam", b =>
                {
                    b.Property<int>("TeamId")
                        .HasColumnType("integer");

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NormalizedAbbreviation")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("NormalizedFullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("SportId")
                        .HasColumnType("integer");

                    b.HasKey("TeamId");

                    b.HasIndex("SportId");

                    b.ToTable("TwitterTeams", (string)null);
                });

            modelBuilder.Entity("RotoMonsterTwitter.Model.Entities.TwitterTeamAlias", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Alias")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("NormalizedAlias")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedAlias");

                    b.HasIndex("TeamId");

                    b.ToTable("TwitterTeamAliases", (string)null);
                });

            modelBuilder.Entity("RotoMonsterTwitter.Model.Entities.Tweet", b =>
                {
                    b.HasOne("RotoMonsterTwitter.Model.Entities.TweetUser", "TweetUser")
                        .WithMany()
                        .HasForeignKey("TwitterUserId")
                        .HasPrincipalKey("TwitterUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TweetUser");
                });

            modelBuilder.Entity("RotoMonsterTwitter.Model.Entities.TweetKeyword", b =>
                {
                    b.HasOne("RotoMonsterTwitter.Model.Entities.TwitterKeyword", "Keyword")
                        .WithMany()
                        .HasForeignKey("KeywordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RotoMonsterTwitter.Model.Entities.Tweet", "Tweet")
                        .WithMany("Keywords")
                        .HasForeignKey("TweetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Keyword");

                    b.Navigation("Tweet");
                });

            modelBuilder.Entity("RotoMonsterTwitter.Model.Entities.TweetMedia", b =>
                {
                    b.HasOne("RotoMonsterTwitter.Model.Entities.Tweet", "Tweet")
                        .WithMany("Media")
                        .HasForeignKey("TweetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tweet");
                });

            modelBuilder.Entity("RotoMonsterTwitter.Model.Entities.TweetPlayer", b =>
                {
                    b.HasOne("RotoMonsterTwitter.Model.Entities.TwitterPlayer", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RotoMonsterTwitter.Model.Entities.Tweet", "Tweet")
                        .WithMany()
                        .HasForeignKey("TweetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("Tweet");
                });

            modelBuilder.Entity("RotoMonsterTwitter.Model.Entities.TweetTeam", b =>
                {
                    b.HasOne("RotoMonsterTwitter.Model.Entities.TwitterTeam", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RotoMonsterTwitter.Model.Entities.Tweet", "Tweet")
                        .WithMany()
                        .HasForeignKey("TweetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");

                    b.Navigation("Tweet");
                });

            modelBuilder.Entity("RotoMonsterTwitter.Model.Entities.TwitterPlayerAlias", b =>
                {
                    b.HasOne("RotoMonsterTwitter.Model.Entities.TwitterPlayer", "Player")
                        .WithMany("Aliases")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("RotoMonsterTwitter.Model.Entities.TwitterTeamAlias", b =>
                {
                    b.HasOne("RotoMonsterTwitter.Model.Entities.TwitterTeam", "Team")
                        .WithMany("Aliases")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("RotoMonsterTwitter.Model.Entities.Tweet", b =>
                {
                    b.Navigation("Keywords");

                    b.Navigation("Media");
                });

            modelBuilder.Entity("RotoMonsterTwitter.Model.Entities.TwitterPlayer", b =>
                {
                    b.Navigation("Aliases");
                });

            modelBuilder.Entity("RotoMonsterTwitter.Model.Entities.TwitterTeam", b =>
                {
                    b.Navigation("Aliases");
                });
#pragma warning restore 612, 618
        }
    }
}
