// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RotoMonsterTwitter.Model.Data;

#nullable disable

namespace RotoMonsterTwitter.Model.Migrations
{
    [DbContext(typeof(TwitterDbContext))]
    partial class TwitterDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RotoMonsterTwitter.Model.Entities.Tweet", b =>
                {
                    b.Property<string>("TweetId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateAdded")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Followers")
                        .HasColumnType("integer");

                    b.Property<bool?>("IsRetweet")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsSourceTweet")
                        .HasColumnType("boolean");

                    b.Property<int?>("RetweetCount")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("RetweetDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RetweetUserScreenName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SourceTweetId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("SourceTweetUserScreenName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("SportId")
                        .HasColumnType("integer");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TwitterUserId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("TweetId");

                    b.HasIndex("CreatedDate");

                    b.HasIndex("TwitterUserId");

                    b.HasIndex("SportId", "CreatedDate");

                    b.ToTable("Tweets", (string)null);
                });

            modelBuilder.Entity("RotoMonsterTwitter.Model.Entities.TweetMedia", b =>
                {
                    b.Property<string>("TweetId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<short>("DisplayOrder")
                        .HasColumnType("smallint");

                    b.Property<int?>("DurationMillis")
                        .HasColumnType("integer");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("VideoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("TweetId", "DisplayOrder");

                    b.ToTable("TweetMedia", (string)null);
                });

            modelBuilder.Entity("RotoMonsterTwitter.Model.Entities.TweetUser", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsBlueVerified")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ScreenUsername")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("TwitterUserId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("VerifiedType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("ScreenUsername")
                        .IsUnique();

                    b.HasIndex("TwitterUserId")
                        .IsUnique();

                    b.ToTable("TweetUsers", (string)null);
                });

            modelBuilder.Entity("RotoMonsterTwitter.Model.Entities.TwitterList", b =>
                {
                    b.Property<long>("ListId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastFetchedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("LastFetchedUnix")
                        .HasColumnType("bigint");

                    b.Property<int>("LastTweetCount")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("SportId")
                        .HasColumnType("integer");

                    b.HasKey("ListId");

                    b.HasIndex("SportId");

                    b.ToTable("TwitterLists", (string)null);
                });

            modelBuilder.Entity("RotoMonsterTwitter.Model.Entities.Tweet", b =>
                {
                    b.HasOne("RotoMonsterTwitter.Model.Entities.TweetUser", "TweetUser")
                        .WithMany()
                        .HasForeignKey("TwitterUserId")
                        .HasPrincipalKey("TwitterUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TweetUser");
                });

            modelBuilder.Entity("RotoMonsterTwitter.Model.Entities.TweetMedia", b =>
                {
                    b.HasOne("RotoMonsterTwitter.Model.Entities.Tweet", "Tweet")
                        .WithMany("Media")
                        .HasForeignKey("TweetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tweet");
                });

            modelBuilder.Entity("RotoMonsterTwitter.Model.Entities.Tweet", b =>
                {
                    b.Navigation("Media");
                });
#pragma warning restore 612, 618
        }
    }
}
